### PR TITLE
Coming soon activity

### PR DESCRIPTION
**Pull request by rajaybitter**
Created a temp activity to say coming also made it so that the temp activity loads first instead of the splash activity.

### CODE REVIEW

**Comment by JavonDavis** [comment]
@rajaybitter This is way too dry. Do me a favor and load the splash page and as it loads just have an alert popup saying "App is currently under construction for Research Days 2017. Coming Soon!" when they dismiss the popup close the app.

**Comment by JavonDavis** [comment]
@rajaybitter you'll need to rebase off master as well I pushed a commit with a change to the gitignore and the build.gradle

**Comment by rajaybitter** [comment]
Added the alert, title was made the color red and alert shifted a little below the logo.

**Comment by rajaybitter** [comment]
@JA-VON review and let me know if i'ts acceptable.

**Comment by JavonDavis** [comment]
@rajaybitter Change Feburary to February and resend it so I can just merge it from here.

**Comment by JavonDavis** [comment]
Everything else is good! As soon as we get the data from the faculty I'll let you know, you can get started on building out the functionality of the app.

**Comment by JavonDavis** [comment]
@rajaybitter you closed it before I merged lol I'll close it after the merge

**Pull request merged**
